# 开发环境配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sso?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: ssouser
    password: DB_PASSWORD_VALUE

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: false # 开发环境可以先禁用，手动创建表

logging:
  level:
    root: INFO
    site.cocow.sso: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
